### ISSUE TITLE
Circulator and transit lines

### ISSUE THREAD

**Issue by ebrelsford** [carfreekeywest/data#4]
* [x] circulator routes
* [x] bus routes

**Comment by kchanba** [comment]
Here is the PDF, I will try to get these in GIS from Chris
http://www.cityofkeywest-fl.gov/egov/documents/1488230814_6672.pdf

**Comment by ebrelsford** [comment]
We now have the bus routes, I assume we still need the circulator route?

**Comment by kchanba** [comment]
Great! Circulator we'll have to trace from my map I believe.

**Comment by ebrelsford** [comment]
Will wait to style bus routes until larger print map styled

**Comment by ebrelsford** [comment]
Traced circulator route
