### ISSUE TITLE
Other businesses

### ISSUE THREAD

**Issue by ebrelsford** [carfreekeywest/data#6]
How do we choose which to show?

**Comment by kchanba** [comment]
Hey @ebrelsford! Here's a link to a spreadsheet of Names/Addresses/Categories for the POI layer. Some of these may change and i'll post adjustments. There are also a few addresses I need confirmation on. They are highlighted. Let me know if you need anything else!

https://docs.google.com/spreadsheets/d/1VVc3H3bpK7xzKaWla3N9VNPMP4sZXzRw5ootmfcM3eI/edit#gid=0

**Comment by ebrelsford** [comment]
@kchanba going to close this, along with a number of other issues, as they are in the POI layer.
